"""Blogger Agent: Publishes the project's README as an article on Dev.to.
Gracefully skips if the API key is not configured.

Required env var (add as GitHub Actions secret):
    DEVTO_API_KEY  — get it from https://dev.to/settings/extensions
"""
import os
import requests


def post_to_devto(project_title, readme_content, repo_url, tags=None):
    """Publish a Dev.to article from the generated README."""
    api_key = os.getenv("DEVTO_API_KEY")
    if not api_key:
        print("  [BLOGGER] DEVTO_API_KEY not set — skipping Dev.to post.")
        return None

    # Append attribution footer
    body = (
        f"{readme_content}\n\n"
        f"---\n\n"
        f"*Auto-generated by [AutoScout](https://github.com/sathiya-22/AutoScout) "
        f"— a daily AI research-to-code pipeline.*"
    )

    payload = {
        "article": {
            "title": project_title,
            "body_markdown": body,
            "published": True,
            "tags": tags or ["ai", "machinelearning", "opensource", "python"],
            "canonical_url": repo_url,
        }
    }

    try:
        response = requests.post(
            "https://dev.to/api/articles",
            json=payload,
            headers={
                "api-key": api_key,
                "Content-Type": "application/json",
            },
            timeout=15,
        )
        if response.status_code == 201:
            article_url = response.json().get("url", "")
            print(f"  [BLOGGER] ✅ Published to Dev.to: {article_url}")
            return article_url
        else:
            print(f"  [BLOGGER] Dev.to post failed: {response.status_code} — {response.text[:200]}")
            return None
    except Exception as e:
        print(f"  [BLOGGER] Dev.to error: {e}")
        return None
